### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by Stricted** [chkelly/gitlab-irc#4]
# unicorn -c config/unicorn.conf -D
config/unicorn.conf:55:in `reload': undefined method `check_client_connection' for #<Unicorn::Configurator:0x0000000086c388> (NoMethodError)
        from /usr/lib/ruby/vendor_ruby/unicorn/configurator.rb:74:in `instance_eval'
        from /usr/lib/ruby/vendor_ruby/unicorn/configurator.rb:74:in `reload'
        from /usr/lib/ruby/vendor_ruby/unicorn/configurator.rb:67:in `initialize'
        from /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:104:in `new'
        from /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:104:in `initialize'
        from /usr/bin/unicorn:121:in `new'
        from /usr/bin/unicorn:121:in `<main>'
master failed to start, check stderr log for details

**Comment by chkelly** [comment]
This is now resolved. I have started updating this app now that I have time. Please ensure that you are running at least ruby-2.2 and have fetched the updates in this repo.
