### ISSUE TITLE
failts to post with 6.9.2 gitlab

### ISSUE THREAD

**Issue by mogorman** [chkelly/gitlab-irc#6]
127.0.0.1 - - [07/Jun/2014 06:43:53] "POST /commit HTTP/1.1" 500 103431 0.0348
ArgumentError - wrong number of arguments (1 for 0):ArgumentError: wrong number of arguments (1 for 0)
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:781:in `block in route'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:474:in `instance_eval'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:474:in `route_eval'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:463:in `block (2 levels) in route!'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:460:in `catch'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:460:in `block in route!'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:439:in `each'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:439:in `route!'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:555:in `dispatch!'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:375:in `block in call!'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:522:in `instance_eval'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:522:in `block in invoke'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:522:in `catch'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:522:in `invoke'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/compat.rb:138:in `invoke'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:375:in `call!'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:364:in `call'
	/var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/showexceptions.rb:24:in `call'
	/var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/methodoverride.rb:24:in `call'
	/var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/commonlogger.rb:20:in `_call'
	/var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/commonlogger.rb:13:in `call'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:898:in `block in call'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:943:in `synchronize'
	/var/lib/gems/1.8/gems/sinatra-0.9.4/lib/sinatra/base.rb:898:in `call'
	/var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/lint.rb:47:in `_call'
	/var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/lint.rb:35:in `call'
	/var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/showexceptions.rb:24:in `call'
	/var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/commonlogger.rb:20:in `_call'
	/var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/commonlogger.rb:13:in `call'
	/var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/chunked.rb:15:in `call'
	/var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/content_length.rb:13:in `call'
	/var/lib/gems/1.8/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client'
	/var/lib/gems/1.8/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
	/var/lib/gems/1.8/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
	/var/lib/gems/1.8/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start'
	/var/lib/gems/1.8/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
	/var/lib/gems/1.8/bin/unicorn:23:in `load'
	/var/lib/gems/1.8/bin/unicorn:23:in `<main>'
127.0.0.1 - - [07/Jun/2014 06:44:33] "POST /commit HTTP/1.1" 500 102535 0.0276
127.0.0.1 - - [07/Jun/2014 06:44:33] "POST /commit HTTP/1.1" 500 102535 0.0280

**Comment by chkelly** [comment]
This is now resolved. I have started updating this app now that I have time. Please ensure that you are running at least ruby-2.2 and have fetched the updates in this repo.
